# Generated by Django 6.0.5 on 2026-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Araba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Süper Spor', 'Süper Spor'), ('Spor Arabalar', 'Spor Arabalar'), ('Lüks Sedanlar', 'Lüks Sedanlar'), ('SUV', 'SUV'), ('Klasikler', 'Klasikler'), ('Hot Hatch', 'Hot Hatch'), ('Elektrikli', 'Elektrikli')], max_length=50)),
                ('marka_model', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('resim_on', models.CharField(max_length=200)),
                ('resim_arka', models.CharField(max_length=200)),
                ('resim_ic', models.CharField(max_length=200)),
                ('motor', models.CharField(max_length=100)),
                ('guc', models.CharField(max_length=50)),
                ('sifir_yuz', models.CharField(max_length=20, verbose_name='0-100 km/s')),
                ('max_hiz', models.CharField(max_length=30, verbose_name='Maksimum Hız')),
                ('agirlik', models.CharField(max_length=30)),
                ('cekis', models.CharField(max_length=50)),
                ('ses', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Araba',
                'verbose_name_plural': 'Arabalar',
                'ordering': ['id'],
            },
        ),
    ]
